### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by rahulcheni** [Zlvsky/One-place#1]
Hello,

How to add users in this project

Thanks,
Rahul C

**Comment by Zlvsky** [comment]
Hello, by default after importing database there is admin user already created.
You can check login and password via phpmyadmin.

If you want to add more users (not clients) navigate to admin panel in app.

**Comment by rahulcheni** [comment]
Hello, unfortunately, the .sql script does not have the insert statement to add a user.

**Comment by rahulcheni** [comment]
I want to add admin user.

**Comment by Zlvsky** [comment]
Okay I have updated the .sql file. Import it again into you database. Remember to specify the name of database in .env file.
Login for that user is: admin and password: admin123.
If it still not gonna work try to insert values to database:
Something like: INSERT into accounts VALUES("", "admin", "admin123", "admin", 2022-10-25);

**Comment by rahulcheni** [comment]
Reimported with new .sql file. Now I can see the admin account inserted in the accounts table. But still, it is not letting me log in with the admin user. I have followed your installation steps. Am I missing some steps here?
Thanks!

**Comment by Zlvsky** [comment]
Have you created .env file in project root directory? You need to specify database name here, if you imported the file it should look like this. Keep in mind that it may be different on your computer 
```
DB_HOST='127.0.0.1'
DB_USER='root'
DB_PASSWORD=''
DATABASE='one-place'
```
